### ISSUE TITLE
Callback functions

### ISSUE THREAD

**Issue by bencz** [VROOM-Project/pyvroom#100]
Is there any way to have callback functions when start to analyze  a service?
For example, this jsprit case: https://github.com/graphhopper/jsprit/blob/master/docs/Walkthrough%20%20%20Constraints.md

Another example case, let's suppose I have N jobs to be done, all leaving the same location, but I would like to separate them by quadrants, taking the lat/long of the deposit and dividing it into 4 and also, add per division, a buffer where the algorithm can consider the point, to form a pair/route
With this, I would not form routes where the points are in opposite directions in relation to the lat/long of the deposit point

![image](https://github.com/VROOM-Project/pyvroom/assets/1174448/e285ae26-c6a8-495a-942f-cb245e5ec51a)

Well... the ideia is a callback funcion, could be possible to add some custom logic to help in route creation

**Comment by bencz** [comment]
The link does not contain the word callback, I already sent the link referring to the documentation, of a call that the routing system makes, to check if the point it is looking at, can be classified to enter the route it is calculating

I think more specifically, it's in this part: https://github.com/graphhopper/jsprit/blob/master/docs/Walkthrough%20%20%20Constraints.md#hard-constraints

Anyway, the  idea would be to be able to 'customize' the creation of routes, something that allows you to create customized logic

**Comment by bencz** [comment]
I read the entire issue you sent now, yes, the idea would be basically like what was described there

**Comment by jcoupey** [comment]
> the idea would be basically like what was described there

Right, then the answer would be basically the same as the one there. ;-)

**Comment by jcoupey** [comment]
> the idea would be basically like what was described there

Right, then the answer would be basically the same as the one there. ;-)
