### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by daniel-ruiz** [VROOM-Project/pyvroom#101]
Thank you for maintaining this amazing project!

We are using it in a Python project that we'd like to update to Python 3.12, but we found out there were no compiled binaries of `pyvroom` for this Python version yet. Looking through the commit history, we've found [this change](https://github.com/VROOM-Project/pyvroom/commit/56856ec6a9e590c7fdc860a908f4464a61ade236) where the build pipeline is ignoring the Python 3.12 build. 

Are there any blocks for adapting `pyvroom` to Python 3.12? I'm not familiar with the source code, but I'd be glad to help with the proper introduction to the issue.

Thanks in advance 😊

**Comment by jonathf** [comment]
Thanks for your kind words.

Looks like getting 3.12 up and running is trivial. Just fixing an unrelated technical difficulty first (see #102). I'll let you know when it is ready.

**Comment by daniel-ruiz** [comment]
Thank you so much! That was a real quick response 🚀

**Comment by jonathf** [comment]
No worries. Issues is fixed now, and new version is being built as we speak. Version 1.13.4 should be ready in about 20 minutes. Let me know if that is not the case.

**Comment by daniel-ruiz** [comment]
I already see it available in PyPI: https://pypi.org/project/pyvroom/1.13.4/

Thank you so much 😊
