### ISSUE TITLE
Upgrade vroom to 1.14.0

### ISSUE THREAD

**Issue by SebMilardo** [VROOM-Project/pyvroom#105]
Hi all!

Thank you for the amazing work! I would like to know if you are planning to upgrade vroom to version 1.14.0. I am trying to set the distances matrix of a vroom.Input but it looks like this feature is not available in https://github.com/VROOM-Project/vroom/commit/e2653a46f5e84d52032f2f47788e3898d9ef98fc

**Comment by jonathf** [comment]
Absolutly. I just haven't gotten around to it yet. It is at the top of my todo list for pyvroom.

**Comment by SebMilardo** [comment]
This is great! At the moment I'm poking around as I have just brutally replaced vroom with the 1.14.0 version. Obviously I'm getting lots of errors and I'm trying to fix them step by step. If I get something working I might open a PR.

**Comment by jonathf** [comment]
Pyvroom version 1.14.0 has now been released!
