### ISSUE TITLE
Wheels for arm64

### ISSUE THREAD

**Issue by merschformann** [VROOM-Project/pyvroom#108]
Hey everyone,

First of all, thank you so much for the work on this project. It is performing really well and is awesome to use.

We ran into some problems when hosting pyvroom on our platform, though, as we are currently limited to arm64 architecture. This is subject to change in future; however, we wanted to support pyvroom earlier. For this, I created a small project that compiles pyvroom wheels for additional platforms as a temporary solution. You can find it here: [pyvroomwheels](https://github.com/merschformann/pyvroom-wheels).

This was done to quickly unblock us; however, I would be happy to contribute something back to the main project if you are interested / it makes sense.

Thanks again for the great work!

Best,
Marius

**Comment by jonathf** [comment]
That is very neat! If you can contribute a patch that would be much appriciated!

**Comment by merschformann** [comment]
I only did [subtle changes to the build](https://github.com/VROOM-Project/pyvroom/compare/main...merschformann:pyvroom:main). I made some more changes to the release workflow, but most were just needed to make the additional package and its builds work ([pyvroomwheels](https://pypi.org/project/pyvroomwheels/#files)).

Anyway, the real challenge is in the two self-hosted machines (runners - [rpi](https://github.com/merschformann/pyvroom-wheels/blob/main/.github/workflows/release.yml#L21-L24) & [mac-mini](https://github.com/merschformann/pyvroom-wheels/blob/main/.github/workflows/release.yml#L29-L32)) that I am hosting for this. It's at least a security concern for both sides to be discussed, even if I am willing to maintain them further in the interest of this project. :blush:
Happy to continue the discussion though. :relaxed:

**Comment by merschformann** [comment]
By the way, there seem to be [Github-hosted arm64 runners](https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/) for open source on the horizon. So, maybe just a temp solution is required. :shrug:

**Comment by nilsnolde** [comment]
We're past the "horizon" stage on arm64 macs:) We already use that since a while: https://github.com/valhalla/valhalla/blob/master/.github/workflows/osx.yml.

**Comment by merschformann** [comment]
Oooh, I didn't realize. Good to know. Well, that should make things simpler, right? :joy_cat: 

At least for darwin/arm64 that is. There seems to be [no docker available on the macos runners](https://github.com/merschformann/pyvroom-wheels/actions/runs/9523145040/job/26254019823). :monocle_face: 
So, that may require a hack.

**Comment by jonathf** [comment]
Today I took a stab at getting both the current arches to work (intel-mac was down) and some new ones (arm-mac and arm-linux). Here is my current status:

* intel-mac is back up
* arm-mac now works as expected on a native runner and is quite fast.
* arm-linux works through Qemu so it is slow. A 10 min build is now being stretched out to about 50 min.

To achieve this I had to increase the requerments a bit both for Python (3.9) and Mac (13 on intel, 14 on arm).

I don't have arm64 linux so please try it out and let us know how it works with `pip install pyvroom==1.13.6.dev7`.

**Comment by merschformann** [comment]
It works perfectly on our infra and on my rpi. Thank you so much! :hugs:

**Comment by jonathf** [comment]
Looks good on my M1 as well. I just released 1.13.6.

As you noted, native arm is on the horizon. I'll need to revisit this when that happens so we can get the build time down.
