### ISSUE TITLE
Adding a new developer

### ISSUE THREAD

**Issue by jonathf** [VROOM-Project/pyvroom#113]
@jcoupey,
would it be okay to elevate @SebMilardo to developer status? He has contributed with high quality code and has been instrumental for adding vroom 1.14 support, and it will save me time if he could make git tags that trigger full releases as he sees fit.

@SebMilardo,
is this fine with you?

Very simple workflow to follow:

* Make dev releases with git tag `X.Y.Z-devN` to test code as you see fit.
* Do PRs and reviews (as before) to get code into `main`.
* Make releases with  git tag `X.Y.Z` on `main` branch as needed.

**Comment by SebMilardo** [comment]
Always happy to help :-)

**Comment by jcoupey** [comment]
Hey, as it happens I've had the exact same thought just yesterday and wanted to touch base!

@jonathf you're probably able to grant the status yourself, or else feel free to ping me if I need to do anything.

**Comment by jonathf** [comment]
Great.

@jcoupey, it does not look like I am.

**Comment by SebMilardo** [comment]
Accepted, Thank you!
