### ISSUE TITLE
Hi, I tried running the example code given in the documentation but encountered errors. Please let me know how to resolve this.

### ISSUE THREAD

**Issue by hns0707** [VROOM-Project/pyvroom#120]
problem_instance = vroom.Input(
            servers={"auto": "valhalla1.openstreetmap.de:443"},
            router=vroom._vroom.ROUTER.VALHALLA
        )

        problem_instance.add_vehicle(vroom.Vehicle(1, start=(51.5075,  -0.1279), profile="auto"))

        problem_instance.add_job([
            vroom.Job(1, location=(51.5075,  -0.1279)),
            vroom.Job(2, location=(51.5077239943, -0.1310421061)),
            vroom.Job(3, location=(51.5098275520, -0.1348400078)),
        ])

        sol = problem_instance.solve(exploration_level=5, nb_threads=4)
        print(sol.summary.distance)

on Above code i'm getting "Valhalla matrix error (No suitable edges near location)." can you please help me out to fix this issue

**Comment by hns0707** [comment]
it worked for me. Thank you

**Comment by hns0707** [comment]
VroomRoutingException at /pmd/get_route/
Valhalla matrix error (Path distance exceeds the max distance limit: 400000 meters).

I am encountering the error mentioned above. Could you please assist me?


problem_instance = vroom.Input(
        servers={"auto": "valhalla1.openstreetmap.de:443"},
        router=vroom._vroom.ROUTER.VALHALLA
    )
    vehicles = []
    for tech in technicians:
        shift_start_seconds = time_to_seconds(tech['shift_start'])
        shift_end_seconds = time_to_seconds(tech['shift_end'])
        print('shift_start_seconds',shift_start_seconds)
        vehicle = vroom.Vehicle(
            id=tech['id'],
            start=(tech['lon'],tech['lat']),
            profile="auto",
            max_distance=4294967295,
        )
        vehicles.append(vehicle)
    problem_instance.add_vehicle(vehicles)

   
    jobs = []
    for site in sites:
        service_time = site['task_time'] * 60  # Task time in seconds
    
        job = vroom.Job(
            id=site['id'],
            service=service_time,
            skills={},
            location=(site['lon'], site['lat'])
        )

        jobs.append(job)

    problem_instance.add_job(jobs)

**Comment by jcoupey** [comment]
That is a routing error related to the coordinates you're supplying and how the Valhalla instance is configured. If you need to adjust the Valhalla config, you should consider running your own instance.

I think we can close for the optimization-related part here.
