### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/pyvroom#22]
@jonathf I see there are already a couple of `0.*` tags, probably because you consider this is still WIP. Once you feel this is more mature, it would be interesting to have a simple tagging convention between this repo and the upstream C++ code repo.

What we do for `vroom-docker` is that whenever there is a new `vroom` release, the docker setup is updated and the same tag is pushed there (e.g. `v1.11.0`). The good part is that it makes it clear what version people can expect to use, be it from C++, Docker or python.

The other advantage is that it would provide some guarantee for users that the `pyvroom` bindings are expected to work with the same `vroom` tag. The matching might become harder to describe otherwise, for example if there is a breaking change in C++ code that requires adjustments to the bindings.

**Comment by jonathf** [comment]
Yes, absolutly.

But first I need ot complete adding polish, docstrings and tests.

My dayjob kicks in next week, so development will slow down a bit now. But I hope to get to a place I could call stable within a couple of months.

BTW, Github claims I don't have write access here. Mind giving me back some of the admin rights?

**Comment by jcoupey** [comment]
Great, feel free to close this ticket anytime then.

> BTW, Github claims I don't have write access here

Too much going back and forth with rights and access, you seemed to be indeed erased from the members for this repo. I just invited you back with Maintain role.

**Comment by jonathf** [comment]
Thank you.

Last thing, can you remove the need for review from the main branch?
Until the code is stabilized I want the ability to push forward faster.

**Comment by jcoupey** [comment]
I removed the branch protection rule for `main` in the settings, looks like it did the trick.
