### ISSUE TITLE
Enable CodeCov

### ISSUE THREAD

**Issue by jonathf** [VROOM-Project/pyvroom#30]
@jcoupey, I'd like to set up code coverage for the pyvroom project on codecov.io.

Do you mind going in there and enable coverage for pyvroom?
In addition, I'd also appriciated if you placed the generate token in repo's secrets under the name `CODECOV_TOKEN`. It is not a hard requirement for public repos, but I've had some trouble without it in the past.

That might be all I need, but its been a while since I set it up, and it is a first for me with something where C++ code is involved. So we'll see where this goes.

**Comment by jcoupey** [comment]
I've registered on codecov and added the `CODECOV_TOKEN` secret for this repo. It should activate automatically once you upload a report. Let me know if anything else is needed on my side.

**Comment by jonathf** [comment]
It works now, thank you.

**Comment by jonathf** [comment]
I've tried it out a little bit and the results are flaky. Many commits do not process.

Looks like some recommed installing the [codecov github app](https://github.com/apps/codecov). Do you mind giving that a try, @jcoupey?

**Comment by jcoupey** [comment]
I just followed the steps from the notification I got after your request. It should be installed for the `pyvroom` repo, let me know if more actions are required on my side.

**Comment by jonathf** [comment]
Excellent. Now it looks like it behaves as it should. :)
