### ISSUE TITLE
ORS routing not working

### ISSUE THREAD

**Issue by MAYURNAGAR-7069** [VROOM-Project/pyvroom#60]
![Screenshot from 2022-07-22 13-07-21](https://user-images.githubusercontent.com/109788788/180388671-12efb979-661c-4563-a50a-b4e94b518f48.png)

This is my code 

when i use ORS routing, in solve it is giving error like

**vroom._vroom.VroomRoutingException: VROOM compiled without routing support.**

**Comment by jcoupey** [comment]
Probably the version of `vroom` used has been compiled without routing support. This option has been enabled with https://github.com/VROOM-Project/vroom/issues/675, but the default should be to build *with* routing support. How did you install? Did you make any change to the default setup?

**Comment by MAYURNAGAR-7069** [comment]
no i just install pyvroom from 

[pyvroom](https://github.com/VROOM-Project/pyvroom)

from here and just use but not worked

**Comment by jcoupey** [comment]
@nilsnolde I see the `vroom` submodule here points to your fork. Any clue on why/if there may be a build without routing enabled?

**Comment by MAYURNAGAR-7069** [comment]
@jcoupey  which python version is support this ORS routing ? So, I can use it as is.
Thank you in adnvance

**Comment by nilsnolde** [comment]
Hm, that’s strange, build options are decided on the setup.py level, which doesn’t exclude the routing module. I can have a look later this week, I’m currently on vacation. 

I don’t understand still how you installed this project @MAYURNAGAR-7069. Did you build from source? If so, can you try the PyPI release?

**Comment by MAYURNAGAR-7069** [comment]
> 

I used PyPI release for install and same error.

**Comment by nilsnolde** [comment]
can you please add a minimum working (and failing) example @MAYURNAGAR-7069? i.e. add the coordinates for matrix, job & vehicle in the code. and **please** copy/paste code, not a picture of code:) that'd help tremendously.

**Comment by MAYURNAGAR-7069** [comment]
`from vroom import _vroom
import vroom
import openrouteservice
from vroom import Input,Vehicle,Job,Location,Break
from odoo import _, api, fields, models

class VROOMOPTIMIZATION(models.Model):
    _name = 'vroom.optimization'
    
    def get_matrix(self,lat_lng):
        metrixs = openrouteservice.distance_matrix.distance_matrix(client, lat_lng, profile='driving-hgv', sources=None, destinations=None, metrics=["duration"], resolve_locations=None, units=None, optimized=True, validate=True, dry_run=None)
        return metrixs
    
    def get_best_route(self,data):
        problem_instance = vroom.Input(router=_vroom.ROUTER.ORS)
        matrixes = self.get_matrix(data.get('lat_lng'))
        problem_instance.set_durations_matrix(
            profile="driving-hgv",
            matrix_input=matrixes.get('durations'),
        )
        problem_instance.add_vehicle([Vehicle(1,description="Vehicle"])
        problem_instance.add_job(2,description="Job Shipment")
        solution = problem_instance.solve(exploration_level=5, nb_threads=4) #IN solve it is giving error
        return solution`
        
        This is my code please check without routing it works but when i use ORS it is not working

**Comment by juanluisrto** [comment]
Ok, I managed to make it work by editing [these lines](https://github.com/VROOM-Project/vroom/blob/9b7165ec568bd0443ca1f01ba2353a504b895157/src/structures/vroom/input/input.cpp#LL48C1-L50C7) and compiling from source. 
```Makefile
#if !USE_ROUTING
  throw RoutingException("VROOM compiled without routing support.");
#endif
```
`USE_ROUTING` is defaulted to True in the Makefile at compilation time. I don't know C++ but it seems to me that the code is relying on an env var which is just not there at execution time. Does that make sense?

**Comment by nilsnolde** [comment]
Hm, yeah, it might be that routing actually never worked :sweat_smile: vroom's Makefile default USE_ROUTING to true, but we're compiling from source here and we don't add that explicitly in setup.py, which we should. Tests are not covering the integration (it seems) and I never really used this package yet.

I'll quickly draft a PR with that one-liner, but no time for testing now.. Also skeptical about testing this, it's a bigger job and not even upstream vroom tests any HTTP integration IIRC.

**Comment by nilsnolde** [comment]
@juanluisrto can you please try a source build with #76 ?

**Comment by juanluisrto** [comment]
@nilsnolde That change solves the problem. Thanks!
