### ISSUE TITLE
I can not build pyvroom from source code

### ISSUE THREAD

**Issue by MAYURNAGAR-7069** [VROOM-Project/pyvroom#61]
`(3_8_env) mayurnagar@Mayur-Nagar:~/source/pyvroom$ make develop
python -m pip install -e .
Obtaining file:///home/mayurnagar/source/pyvroom
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages (from pyvroom==0.0.15.dev0+g7f7c755.d20220723) (1.22.4)
Requirement already satisfied: pandas in /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages (from pyvroom==0.0.15.dev0+g7f7c755.d20220723) (1.4.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages (from pandas->pyvroom==0.0.15.dev0+g7f7c755.d20220723) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages (from pandas->pyvroom==0.0.15.dev0+g7f7c755.d20220723) (2022.1)
Requirement already satisfied: six>=1.5 in /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->pyvroom==0.0.15.dev0+g7f7c755.d20220723) (1.16.0)
Installing collected packages: pyvroom
  Attempting uninstall: pyvroom
    Found existing installation: pyvroom 0.0.14
    Uninstalling pyvroom-0.0.14:
      Successfully uninstalled pyvroom-0.0.14
  Running setup.py develop for pyvroom
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [25 lines of output]
        running develop
        running egg_info
        writing src/pyvroom.egg-info/PKG-INFO
        writing dependency_links to src/pyvroom.egg-info/dependency_links.txt
        writing entry points to src/pyvroom.egg-info/entry_points.txt
        writing requirements to src/pyvroom.egg-info/requires.txt
        writing top-level names to src/pyvroom.egg-info/top_level.txt
        reading manifest template 'MANIFEST.in'
        /tmp/pip-build-env-7tofpok0/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /tmp/pip-build-env-7tofpok0/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        warning: no files found matching '*' under directory 'vroom'
        adding license file 'LICENSE'
        writing manifest file 'src/pyvroom.egg-info/SOURCES.txt'
        running build_ext
        x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Isrc -Ivroom/src -Ivroom/include -Ivroom/include/cxxopts/include -I/home/mayurnagar/.conan/data/openssl/1.1.1m/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/include -I/home/mayurnagar/.conan/data/asio/1.21.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/mayurnagar/source/3_8_env/include -I/usr/include/python3.8 -I/home/mayurnagar/source/3_8_env/include -I/usr/include/python3.8 -c flagcheck.cpp -o flagcheck.o -std=c++17
        building '_vroom' extension
        x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-7tofpok0/overlay/lib/python3.8/site-packages/pybind11/include -Isrc -Ivroom/src -Ivroom/include -Ivroom/include/cxxopts/include -I/home/mayurnagar/.conan/data/openssl/1.1.1m/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/include -I/home/mayurnagar/.conan/data/asio/1.21.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/mayurnagar/source/3_8_env/include -I/usr/include/python3.8 -I/home/mayurnagar/source/3_8_env/include -I/usr/include/python3.8 -c src/_vroom.cpp -o build/temp.linux-x86_64-cpython-38/src/_vroom.o -std=c++17 -fvisibility=hidden -g0 -MMD -MP -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -DUSE_PYTHON_BINDINGS
        In file included from src/_vroom.cpp:1:
        src/bind/_main.cpp:4:10: fatal error: main.cpp: No such file or directory
            4 | #include "main.cpp"
              |          ^~~~~~~~~~
        compilation terminated.
        error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of pyvroom
  Moving to /home/mayurnagar/source/3_8_env/bin/vroom
   from /tmp/pip-uninstall-_3_etl4z/vroom
  Moving to /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages/pyvroom-0.0.14.dist-info/
   from /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages/~yvroom-0.0.14.dist-info
  Moving to /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages/pyvroom.libs/
   from /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages/~yvroom.libs
  Moving to /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages/vroom/
   from /home/mayurnagar/source/3_8_env/lib/python3.8/site-packages/~room
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [25 lines of output]
    running develop
    running egg_info
    writing src/pyvroom.egg-info/PKG-INFO
    writing dependency_links to src/pyvroom.egg-info/dependency_links.txt
    writing entry points to src/pyvroom.egg-info/entry_points.txt
    writing requirements to src/pyvroom.egg-info/requires.txt
    writing top-level names to src/pyvroom.egg-info/top_level.txt
    reading manifest template 'MANIFEST.in'
    /tmp/pip-build-env-7tofpok0/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /tmp/pip-build-env-7tofpok0/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    warning: no files found matching '*' under directory 'vroom'
    adding license file 'LICENSE'
    writing manifest file 'src/pyvroom.egg-info/SOURCES.txt'
    running build_ext
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Isrc -Ivroom/src -Ivroom/include -Ivroom/include/cxxopts/include -I/home/mayurnagar/.conan/data/openssl/1.1.1m/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/include -I/home/mayurnagar/.conan/data/asio/1.21.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/mayurnagar/source/3_8_env/include -I/usr/include/python3.8 -I/home/mayurnagar/source/3_8_env/include -I/usr/include/python3.8 -c flagcheck.cpp -o flagcheck.o -std=c++17
    building '_vroom' extension
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-7tofpok0/overlay/lib/python3.8/site-packages/pybind11/include -Isrc -Ivroom/src -Ivroom/include -Ivroom/include/cxxopts/include -I/home/mayurnagar/.conan/data/openssl/1.1.1m/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/include -I/home/mayurnagar/.conan/data/asio/1.21.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/mayurnagar/source/3_8_env/include -I/usr/include/python3.8 -I/home/mayurnagar/source/3_8_env/include -I/usr/include/python3.8 -c src/_vroom.cpp -o build/temp.linux-x86_64-cpython-38/src/_vroom.o -std=c++17 -fvisibility=hidden -g0 -MMD -MP -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -DUSE_PYTHON_BINDINGS
    In file included from src/_vroom.cpp:1:
    src/bind/_main.cpp:4:10: fatal error: main.cpp: No such file or directory
        4 | #include "main.cpp"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
make: *** [Makefile:11: develop] Error 1
`

**This error comes when i try to build pyvroom**

**Comment by nilsnolde** [comment]
Looks like you forgot to do a “git submodule update —init —recursive”? Is this related to #60 ?

**Comment by nilsnolde** [comment]
yeah, just built `master` successfully myself, you were missing the submodule update cmd

**Comment by MAYURNAGAR-7069** [comment]
thank you i got it now @nilsnolde
