### ISSUE TITLE
Time Windows example?

### ISSUE THREAD

**Issue by fpolloa** [VROOM-Project/pyvroom#63]
Excuse me for bringing this in here, couldn't find a forum where to discuss this.

How would one proceed to solve a CVRP with TW using pyvroom?

Thanks!

**Comment by jcoupey** [comment]
Did you check the [readme example](https://github.com/VROOM-Project/pyvroom#basic-usage)? It looks to me that you should simply adjust how the tasks are defined via `vroom.Job`.

Constructing a job object happens [here](https://github.com/VROOM-Project/pyvroom/blob/7f7c755c763ddc416455ea8c5168b53ae1477084/src/vroom/job.py#L132-L144) in python.

**Comment by fpolloa** [comment]
Hi jcoupey, thanks for getting back! I'll leave my code for future references.

```
from __future__ import all_feature_names
import vroom

problem_instance = vroom.Input()
d_matrix = []
for i in N:
    matrix_row = []
    for j in N:
        if i != j:
            matrix_row.append(t_ij[(i,j)])
        else:
            matrix_row.append(0)
    d_matrix.append(matrix_row)

problem_instance.set_durations_matrix(
    profile="truck",
    matrix_input= d_matrix)
for i in range(1,nb_trucks+1):
    problem_instance.add_vehicle([vroom.Vehicle(i, start=0, end=0, capacity=[capa], time_window=(0,T))])

for i in N[1:]:
    problem_instance.add_job([vroom.Job(i, location=i, service=s[i],delivery=[q[i]],time_windows=[vroom.TimeWindow(e[i],l[i])])])

solution = problem_instance.solve(exploration_level=5, nb_threads=4)
```
