### ISSUE TITLE
Significant figures in results

### ISSUE THREAD

**Issue by fpolloa** [VROOM-Project/pyvroom#64]
I have noticed there aren't any decimals in results. Further, when calculating the cost manually I normally get to a different result. Is the solver dropping decimals in the process ? Is there a way to impede this?

code to calculate cost:
```
cost = 0
for i in routes.keys():
    for j in range(len(routes[i])-1):
        cost += d_ij[(routes[i][j],routes[i][j+1])]
```

**Comment by jcoupey** [comment]
This project provides bindings to the upstream `vroom` project written in C++. So you want to check out [the docs there](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md). All costs and durations are indeed integers.
