### ISSUE TITLE
Missing coordinates for routing engine

### ISSUE THREAD

**Issue by fahadahaf** [VROOM-Project/pyvroom#78]
Hi,
I am trying to replicate the example given in pyvroom readme, but getting the following error:
```
---------------------------------------------------------------------------
VroomInputException                       Traceback (most recent call last)
<ipython-input-12-24e85c7bac87> in <module>
----> 1 solution = problem_instance.solve(exploration_level=5, nb_threads=4)

~/.local/lib/python3.8/site-packages/vroom/input/input.py in solve(self, exploration_level, nb_threads)
    310     ) -> Solution:
    311         return Solution(
--> 312             self._solve(
    313                 exploration_level=exploration_level,
    314                 nb_threads=nb_threads,

VroomInputException: Missing coordinates for routing engine.
```

I get this when running the following:
`solution = problem_instance.solve(exploration_level=5, nb_threads=4)`

**Comment by jonathf** [comment]
Sounds like some of the lines from the example hasn't registered.

Mind posting version info about your platform, OS, python and vroom?

**Comment by fahadahaf** [comment]
Here are the details:
pyvroom: 1.13.1
OS: MacOS Monterey (12.5)
python: 3.8.5

**Comment by fahadahaf** [comment]
It works now, my mistake was I was using "vehicle" as profile and not "car".
Thank you.
