### ISSUE TITLE
max_travel_time gets automatically multiplied by 100

### ISSUE THREAD

**Issue by juanluisrto** [VROOM-Project/pyvroom#79]
`Vehicle.max_travel_time` gets multiplied by 100 for no apparent reason. 
I have tried to find the source of this bug, but I am not sure if this is happening in `pyvroom` or in `vroom`. 

```python
import vroom

v1 = vroom.Vehicle(1, start = 0, max_travel_time= 5)
print(v1._max_travel_time)

v2 = vroom.Vehicle(2, start = 0, max_travel_time= 23)
print(v2._max_travel_time)
```
**Output**
```
500
2300
```
**Expected output**
```
5
23
```

**Comment by jonathf** [comment]
`_max_travel_time` is only for internal use, but your argument still holds for the public facing `max_travel_time`.

I've made a fix now and released 1.13.2 which should fix your problem.
