### ISSUE TITLE
VroomInputException: Missing location index.

### ISSUE THREAD

**Issue by L0G1C06** [VROOM-Project/pyvroom#86]
I am trying to use pyvroom for real addresses, ie I pass in a .json file the longitude and latitude of Jobs and Vehicles. However, when I perform this treatment, in theory, it follows the standard requested by the library, but one doubt I have is that in the "location" flag of add_job, it says that you can put two ways to start location, an integer or two values that will be automatically interpreted as longitude and latitude. But I would also like to know how I could instead of passing these integers, real longitude and latitude, example: Latitude = 2.2384643554687504, Longitude = 48.93242424920101

**Comment by jcoupey** [comment]
See [this documentation note](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#task-locations) on locations. The bottom line is: if you want to input coordinates, you should do so consistently and submit no location index at all.

**Comment by L0G1C06** [comment]
Thanks.
