### ISSUE TITLE
VroomInputException: Invalid profile: car.

### ISSUE THREAD

**Issue by L0G1C06** [VROOM-Project/pyvroom#88]
The lib is not recognizing the car profile, but this profile exist on VROOM

**Comment by nilsnolde** [comment]
Can you outline a bit more your steps? Input/minimal code & the error (copy/paste, pls no screenshots). My guess is you’re not having any OSRM graph loaded and you’re not providing a custom matrix?

**Comment by L0G1C06** [comment]
I will share here the code

import json
import vroom

# Load the problem instance from the JSON file
json_file_path = "test.json"

# Load the JSON data from the file
with open(json_file_path, "r") as json_file:
    json_data = json.load(json_file)

# Extract the description from the options, if available
options = json_data.get("options", {})
description = options.get("description", "No description available")

# Create an instance of the Input class and pass the server configuration
instance = vroom.Input(servers={"osrm":"172.17.0.4:9966"})
problem_instance = instance.from_json(json_file_path, geometry=True)

vehicles_data = json_data.get("vehicles", [])
vehicle_locations = {}
jobs_data = json_data.get("jobs", [])
for vehicle in vehicles_data:
    start_lat, start_lng = vehicle["start"]
    end_lat, end_lng = vehicle["end"]

for job in jobs_data:
    job_id = job["id"]
    vehicle_id = job.get("vehicle_id")
    if vehicle_id:
        location = vehicle_locations.get(vehicle_id)
        if location:
            job["location"] = location

if jobs_data:
    first_job = jobs_data[0]
    second_job = jobs_data[1]
    third_job = jobs_data[2]
    fourth_job = jobs_data[3]

    first_job_id = first_job["id"]
    second_job_id = second_job["id"]
    third_job_id = third_job["id"]
    fourth_job_id = fourth_job["id"]

    first_job_location = first_job["location"]
    second_job_location = second_job["location"]
    third_job_location = third_job["location"]
    fourth_job_location = fourth_job["location"]

    if first_job_location and second_job_location and third_job_location and fourth_job_location:
        first_job_latitude = first_job["location"][0]
        first_job_longitude = first_job["location"][1]

        second_job_latitude = second_job["location"][0]
        second_job_longitude = second_job["location"][1]

        third_job_latitude = third_job["location"][0]
        third_job_longitude = third_job["location"][1]

        fourth_job_latitude = fourth_job["location"][0]
        fourth_job_longitude = fourth_job["location"][1]

        # Save the information in a separate variable
        first_job_info = {
            "id": first_job_id,
            "latitude": first_job_latitude,
            "longitude": first_job_longitude
        }
        second_job_info = {
            "id": second_job_id,
            "latitude": second_job_latitude,
            "longitude": second_job_longitude
        }
        third_job_info = {
            "id": third_job_id,
            "latitude": third_job_latitude,
            "longitude": third_job_longitude
        }
        fourth_job_info = {
            "id": fourth_job_id,
            "latitude": fourth_job_latitude,
            "longitude": fourth_job_longitude
        }

    else:
        print("No location data available for the first job.")
else:
    print("No jobs found in the JSON data.")

problem_instance.add_vehicle([vroom.Vehicle(vehicle['id'], start=[start_lat, start_lng], end=[end_lat, end_lng], profile="driving-car")])

problem_instance.add_job([vroom.Job(5000, location=[first_job_longitude, first_job_latitude]),
                          vroom.Job(5100, location=[second_job_longitude, second_job_latitude]),
                          vroom.Job(5200, location=[third_job_longitude, third_job_latitude]),
                          vroom.Job(5300, location=[fourth_job_longitude, fourth_job_latitude])])

solution = problem_instance.solve(exploration_level=5, nb_threads=4)

**Comment by L0G1C06** [comment]
The code where i define the profile is the next:

problem_instance.add_vehicle([vroom.Vehicle(vehicle['id'], start=[start_lat, start_lng], end=[end_lat, end_lng], profile="car")])

I am not passing any custom matrix because I am using a JSON file that contains the addresses of all the points, with their respective longitudes and latitudes.

**Comment by L0G1C06** [comment]
This is the form of the JSON file

{
    "jobs": [
      {
        "id": 1,
        "description": "Rue des Binelles, Sèvres",
        "location": [
          2.214431762695313,
          48.82359296752074
        ]
      },
      {
        "id": 2,
        "description": "Quai Henri Pourchasse, Ivry-sur-Seine",
        "location": [
          2.4087524414062504,
          48.813194201165274
        ]
      },
      {
        "id": 3,
        "description": "51, Allée Jules Guesde, Les Pavillons-sous-Bois",
        "location": [
          2.497329711914063,
          48.89948375541988
        ]
      },
      {
        "id": 4,
        "description": "Rue La Boétie, Paris",
        "location": [
          2.309188842773438,
          48.87239311228893
        ]
      }
    ],
    "shipments": [],
    "vehicles": [
      {
        "id": 1,
        "start": [
          2.2384643554687504,
          48.93242424920101
        ],
        "startDescription": "Quai de Bezons, Argenteuil",
        "end": [
          2.2384643554687504,
          48.93242424920101
        ],
        "endDescription": "Quai de Bezons, Argenteuil"
      }
    ],
    "options": {
      "g": true,
    }
  }

**Comment by nilsnolde** [comment]
I meant to copy/paste _all_ relevant code. How you define the `Input` is very important. And wrong in this case: `vroom.Input(servers={"auto":"172.17.0.4:9966"})`. See the PR for more details: https://github.com/VROOM-Project/pyvroom/pull/90/files.

**Comment by nilsnolde** [comment]
I assume this can be closed?
