### ISSUE TITLE
C++20 might break manylinux2014

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/pyvroom#93]
If not with the next vroom version, it'll only be a matter of time until gcc10 will run out of supported C++20 features vroom is using. Currently its running CI with gcc11. I'd suggest to move to [`manylinux_2_28`](https://github.com/pypa/manylinux#manylinux_2_28-almalinux-8-based) eventually, which has gcc12 and is basically CentOS8. I'm working quite a bit on bindings stuff these days and we're using that already, so I could this here too. WDYT @jonathf ?

**Comment by jonathf** [comment]
I am all for it. I wish to contribute, but my time is a little bit limited for the remainder of the month. After that I definetly will give it a shot if you havenn't already gotten to it first.
