### ISSUE TITLE
Get the geometry of the trips

### ISSUE THREAD

**Issue by orlandombaa** [VROOM-Project/pyvroom#94]
Hello!

I just started to use pyvroom.  Is it possible to get the geometry of the trips  in the result? 

Best regards, 
Orlando

**Comment by jonathf** [comment]
I am not sure if I understand the question.

The `solution.routes` object introduced in  [basic usage](https://github.com/VROOM-Project/pyvroom#basic-usage) lists all solution routes as a table from start to finish. Is this the geometry you are looking for?

**Comment by nilsnolde** [comment]
I think the OP is about getting the final paths/routes for the vehicles based on VROOM's optimization.

It's not available yet in the library API but would be very easy to add IMO, we just have to expose the `Solution::set_geometry` function. Even now you can still do it, when using pyvroom as command line, which should print the response to stdout, you can redirect it to a file. Of course in that case you wouldn't need pyvroom, you could do that with upstream vroom as well (though pyvroom is easier to access via PyPI). In your virtual env you should be able to do `vroom <input json>`, it knows the same args as https://github.com/VROOM-Project/vroom/wiki/Usage.

**Comment by orlandombaa** [comment]
Hello every one 

Yes, I was referring to get the geometry of the solutions (the path where the route goes in the street).

**Comment by nilsnolde** [comment]
I'll close since there's an answer, it's just not the most convenient one. Feel free to re-open if the executable path doesn't work.
