### ISSUE TITLE
`max_travel_time` argument not being taken into account

### ISSUE THREAD

**Issue by akyrgiazos** [VROOM-Project/pyvroom#99]
Hi,

I am encountering an issue with the `max_travel_time` for the vehicle component. To my understanding, this specifies the maximum travel duration for a vehicle.
For example, one vehicle of many:

```
vehicle_task = vroom.Vehicle(i, description=f'Technician: {i}', start=0, end=0, max_travel_time=500, capacity=[15])
```

And the call to the problem and solver
```
problem_instance = vroom.Input(amount_size=1)

problem_instance.set_durations_matrix(
     profile="car",
     matrix_input=distances,
)

problem_instance.add_vehicle(vehicles)
problem_instance.add_job(jobs)
solution = problem_instance.solve(exploration_level=5, nb_threads=8)
```

When I checked the solution, by doing the following:
`solution.routes.groupby('vehicle_id').agg({'duration':'sum','id':'size'})`
then in the result I can see the sum of duration for the specific vehicle is exceeded, being greater than the `max_travel_time`.

So I would like to ask whether the understanding of `max_travel_time` is correct or something is not configured correctly. 

Thank you in advance.

**Comment by jonathf** [comment]
Good question. Looks like I pass the argument in correctly so I am guessing this is a backend question.
@jcoupey, do you know what is going on here?

**Comment by akyrgiazos** [comment]
I did some digging and i found that in order to get the total duration I should have done:
`solution.routes.groupby('vehicle_id').agg({'duration':'last','id':'size'})` instead of 
`solution.routes.groupby('vehicle_id').agg({'duration':'sum','id':'size'})`.
Basically not to sum up all the duration as they are already summed up in the output.

**Comment by jcoupey** [comment]
@akyrgiazos shall we close then?

**Comment by akyrgiazos** [comment]
I believe yes. 
Is there in the docs a description of the output? For clarification purposes

**Comment by jcoupey** [comment]
See the upstream documentation: https://github.com/VROOM-Project/vroom/blob/master/docs/API.md.
